# Generated by Django 4.0.5 on 2022-06-14 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        ('empresas', '0002_alter_empresa_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funcionarios', '0003_funcionairo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionairo',
            name='departamentos',
            field=models.ManyToManyField(to='departamentos.departamento'),
        ),
        migrations.AddField(
            model_name='funcionairo',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionairo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
